services:
  # 1. Banco de Dados
  db:
    image: postgres:18
    container_name: repositorio-db
    environment:
      POSTGRES_DB: repositorio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p4ssw0rd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # 2. LLM (Ollama)
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network

  # 3. Backend Java
  backend:
    build: ./backend/repositorio-ppg/repositorio-ppg
    container_name: spring-backend
    environment:
      DB_URL: jdbc:postgresql://db:5432/repositorio
      DB_USER: postgres
      DB_PASSWORD: p4ssw0rd
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  # 4. Microservi√ßo Python
  ai-service:
    build: ./parser
    container_name: python-ai
    environment:
      BACKEND_URL: http://backend:8080/documentos
      OLLAMA_BASE_URL: http://ollama:11434/v1
    ports:
      - "8000:8000"
    depends_on:
      - ollama
      - backend
    networks:
      - app-network

  # 5. Frontend React
  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "5173:80" # Mapeia porta 80 do Nginx para 5173 do seu PC
    depends_on:
      - backend
      - ai-service
    networks:
      - app-network

volumes:
  postgres_data:
  ollama_data:

networks:
  app-network:
    driver: bridge